import {
  AlertTriangle,
  ClipboardList,
  FileText,
  Download,
} from "lucide-react";

import MedicineCard from "./MedicineCard";
import { downloadPrescriptionReport } from "@/utils/pdf";


import type { AnalysisResponse } from "@/types/analysis";

interface Props {
  result: AnalysisResponse;
}

export default function AnalysisCard({
  result,
}: Props) {

  const analysis = result.analysis;

  if (!analysis) {
    return null;
  }

  if (analysis.error) {
    return (
      <div className="mt-10 rounded-3xl border border-red-200 bg-red-50 p-8">
        <p className="text-red-600">
          {analysis.error}
        </p>
      </div>
    );
  }

  return (
    <div className="mt-10 space-y-8">

      {/* Header */}

      <div className="flex items-center justify-between">

        <div>

          <h2 className="text-3xl font-bold">
            AI Prescription Report
          </h2>

          <p className="mt-2 text-neutral-500">
            Generated by MediGen AI
          </p>

        </div>

        <div className="flex items-center gap-3">

          <div className="rounded-full bg-green-100 px-4 py-2 text-sm font-semibold text-green-700">
            ✓ Analysis Complete
          </div>

          <button
            onClick={() => downloadPrescriptionReport(result)}
            className="flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2 text-white transition hover:bg-violet-700"
          >
            <Download size={18} />
            Download PDF
          </button>

        </div>

      </div>

      {/* Medicines */}

      {!!analysis.medicines?.length && (

        <div className="space-y-5">

          {analysis.medicines.map((medicine: any) => (

            <MedicineCard
              key={medicine.name}
              medicine={medicine}
            />

          ))}

        </div>

      )}

      {/* Precautions */}

      {!!analysis.precautions?.length && (

        <div className="rounded-3xl border p-6">

          <div className="flex items-center gap-2">

            <AlertTriangle />

            <h3 className="text-xl font-semibold">
              Precautions
            </h3>

          </div>

          <ul className="mt-5 list-disc space-y-2 pl-5">

            {analysis.precautions.map((item: string) => (

              <li key={item}>
                {item}
              </li>

            ))}

          </ul>

        </div>

      )}

      {/* Summary */}

      {analysis.summary && (

        <div className="rounded-3xl border border-blue-200 bg-blue-50 p-6">

          <div className="flex items-center gap-2">

            <ClipboardList />

            <h3 className="text-xl font-semibold">
              AI Summary
            </h3>

          </div>

          <p className="mt-4 leading-8">
            {analysis.summary}
          </p>

        </div>

      )}

      {/* Disclaimer */}

      {analysis.disclaimer && (

        <div className="rounded-3xl border border-red-200 bg-red-50 p-6">

          <div className="flex items-center gap-2">

            <FileText />

            <h3 className="font-semibold text-red-700">
              Medical Disclaimer
            </h3>

          </div>

          <p className="mt-4 leading-7 text-red-600">
            {analysis.disclaimer}
          </p>

        </div>

      )}

    </div>
  );
}